lib/find_my_personal_web/router.ex
defmodule FindMyPersonalWeb.Router do
  use FindMyPersonalWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FindMyPersonalWeb do
    pipe_through :browser

    get "/teacher/search", TeacherController, :search
    resources "/teacher", TeacherController

    get "/members/search", MemberController, :search
    resources "/members", MemberController

    get "/", PageController, :index
  end

  scope "/api", FindMyPersonalWeb.Api, as: :api do
    pipe_through :api
    resources "/members", MemberController
    resources "/teacher", TeacherController, except: [:new, :edit]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  # if Mix.env() in [:dev, :test] do
  #   import Phoenix.LiveDashboard.Router

  #   scope "/" do
  #     pipe_through :browser
  #     live_dashboard "/dashboard", metrics: FindMyPersonalWeb.Telemetry
  #   end
  # end
end

lib/find_my_personal_web/views/shared_view.ex
defmodule FindMyPersonalWeb.SharedView do
  use FindMyPersonalWeb, :view
end

lib/find_my_personal_web/templates/shared/_header.html.eex
<header>
  <nav>
    <div class="nav-wrapper grey darken-3">
      <%= link "Meu Personal", to: Routes.teacher_path(@conn, :index), class: "brand-logo" %>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <%= render FindMyPersonalWeb.SharedView, "_header_menu.html", assigns %>
      </ul>
    </div>
  </nav>

  <ul class="sidenav" id="mobile-demo">
    <%= render FindMyPersonalWeb.SharedView, "_header_menu.html", assigns %>
  </ul>
</header>

lib/find_my_personal_web/templates/shared/_header_menu.html.eex
 <li><%= link "Personal", to: Routes.teacher_path(@conn, :index)  %></li>
 <li><%= link "Membros", to: Routes.member_path(@conn, :index)  %></li>